In [1]:
import json
import numpy as np
from pickle import load

In [2]:
with open("../Datos/Procesados/jsons/alphapose/halpe26/A/alphapose-results.json") as f:
    halpe = json.load(f)
with open("../Datos/Procesados/jsons/alphapose/results/coco/fast_pose/A/alphapose-results.json") as f:
    fast = json.load(f)
with open("../Datos/Procesados/jsons/alphapose/results/coco/fast_pose_dcn/A/alphapose-results.json") as f:
    dcn = json.load(f)
with open("../Datos/Procesados/jsons/alphapose/results/coco/fast_pose_duc/A/alphapose-results.json") as f:
    duc = json.load(f)
with open("../Datos/Procesados/jsons/alphapose/results/coco/hrnet/A/alphapose-results.json") as f:
    hrn = json.load(f)

### H36M

Es el formato con el que trabaja MotionBERT.

<img src="../Datos/Brutos/h36m_human_model.png" alt="h36m" height=50>

### Halpe26

https://github.com/Fang-Haoshu/Halpe-FullBody

Halpe incluye los keypoints de COCO y los de MPII, junto con alguno extra para los pies (https://github.com/MVIG-SJTU/AlphaPose/issues/655).

<img src="../Datos/Brutos/halpe26_human_model.png" alt="halpe26">

In [3]:
len(halpe[0]["keypoints"])//3

26

In [4]:
np.array(halpe[0]["keypoints"]).reshape(-1, 3)

array([[1.60142548e+02, 6.66209030e+01, 9.40821052e-01],
       [1.72131332e+02, 5.46321068e+01, 9.22449112e-01],
       [1.48153748e+02, 5.46321068e+01, 9.69190300e-01],
       [1.86517899e+02, 6.66209030e+01, 9.69874442e-01],
       [1.36164948e+02, 6.66209030e+01, 9.30694818e-01],
       [2.15291000e+02, 1.33758148e+02, 9.28619981e-01],
       [1.07391846e+02, 1.31360397e+02, 9.05811906e-01],
       [2.32075317e+02, 2.22475235e+02, 8.70064020e-01],
       [8.58120193e+01, 2.17679718e+02, 8.41052532e-01],
       [2.34473068e+02, 2.41657303e+02, 6.00588620e-01],
       [8.10164948e+01, 2.36861786e+02, 7.42394745e-01],
       [1.96108932e+02, 2.34464035e+02, 8.84696305e-01],
       [1.24176163e+02, 2.34464035e+02, 8.54306817e-01],
       [2.10495483e+02, 2.32066269e+02, 5.96602485e-02],
       [9.06075363e+01, 2.22475235e+02, 4.42141891e-02],
       [2.32075317e+02, 2.34464035e+02, 2.30451122e-01],
       [8.34142609e+01, 2.36861786e+02, 3.90900344e-01],
       [1.62540298e+02, 2.34612

### COCO

https://cocodataset.org/#home

Lo forman los primeros 17 puntos de Halpe26.

En su página podemos ver el [formato de los resultados](https://cocodataset.org/#format-results), y el [leaderboard](https://cocodataset.org/#keypoints-leaderboard). Esto puede darnos ideas de otros modelos.

In [5]:
len(fast[0]["keypoints"])//3

17

In [6]:
np.array(fast[0]["keypoints"]).reshape(-1, 3)

array([[1.60142548e+02, 6.42231445e+01, 9.20787573e-01],
       [1.69733582e+02, 5.46321068e+01, 9.31711495e-01],
       [1.48153748e+02, 5.70298653e+01, 9.41004872e-01],
       [1.84120132e+02, 6.66209030e+01, 9.27379012e-01],
       [1.36164948e+02, 6.66209030e+01, 9.21631634e-01],
       [2.15291000e+02, 1.33758148e+02, 8.14521194e-01],
       [1.07391846e+02, 1.31360397e+02, 8.37819338e-01],
       [2.34473068e+02, 2.22475235e+02, 6.96396828e-01],
       [8.34142609e+01, 2.20077469e+02, 6.77533805e-01],
       [2.39268585e+02, 2.53646103e+02, 5.00597395e-02],
       [8.34142609e+01, 2.41657303e+02, 2.40259767e-01],
       [1.96108932e+02, 2.36861786e+02, 6.25032127e-01],
       [1.21778404e+02, 2.34464035e+02, 7.40641832e-01],
       [2.63246185e+02, 2.32066269e+02, 2.63953675e-02],
       [1.16982880e+02, 2.32066269e+02, 5.71921282e-02],
       [2.08097717e+02, 2.32066269e+02, 5.39671108e-02],
       [1.14585121e+02, 2.34464035e+02, 9.19763595e-02]])

### MediaPipe

<img src="../Datos/Brutos/mediapipe_human_model.png" alt="mediapipe">

In [7]:
with open("../Datos/Procesados/alphabet_landmarks_spread.pkl", "rb") as f:
    total_results = load(f)

In [8]:
w, h = total_results["A"]['frame_width'], total_results["A"]['frame_height']
total_results["A"]['landmarks']['pose'][0][[0, 2, 5, 7, 8, 11, 12, 13, 14, 15, 16, 23, 24, 25, 26, 27, 28],:2] * np.array([w, h])

array([[159.74927902,  66.08415127],
       [171.50686264,  55.33866405],
       [148.49415779,  56.70669079],
       [181.88135147,  60.79421997],
       [140.27519226,  63.45798969],
       [217.37522125, 133.05288792],
       [108.95656586, 131.44539356],
       [231.54380798, 215.2667141 ],
       [ 88.30951691, 213.66783142],
       [233.57028961, 276.8651104 ],
       [ 81.88580513, 277.82984734],
       [197.80220032, 283.46451759],
       [121.49507523, 283.45759392],
       [195.34856796, 396.49291992],
       [123.89260292, 393.51350784],
       [192.20159531, 497.2111702 ],
       [119.33254242, 497.21609116]])

In [9]:
w

320

In [10]:
h

240

In [11]:
def coco2halpe(coco_results_path, base_results_path, output_path):
    with open(coco_results_path, 'r') as f:
        coco = json.load(f)
    with open(base_results_path, 'r') as f:
        base = json.load(f)

    for coco_json, base_json in zip(coco, base):
        coco_json["keypoints"].extend(base_json["keypoints"][51:60])

    with open(output_path, 'w') as f:
        json.dump(coco, f)

In [14]:
with open("../Datos/Procesados/jsons/alphapose/coco/fast_pose/A/alphapose-results.json") as f:
    fast = json.load(f)

In [15]:
len(fast[0]["keypoints"])//3

20

In [16]:
np.array(fast[0]["keypoints"]).reshape(-1, 3)

array([[1.60142548e+02, 6.42231445e+01, 9.20787573e-01],
       [1.69733582e+02, 5.46321068e+01, 9.31711495e-01],
       [1.48153748e+02, 5.70298653e+01, 9.41004872e-01],
       [1.84120132e+02, 6.66209030e+01, 9.27379012e-01],
       [1.36164948e+02, 6.66209030e+01, 9.21631634e-01],
       [2.15291000e+02, 1.33758148e+02, 8.14521194e-01],
       [1.07391846e+02, 1.31360397e+02, 8.37819338e-01],
       [2.34473068e+02, 2.22475235e+02, 6.96396828e-01],
       [8.34142609e+01, 2.20077469e+02, 6.77533805e-01],
       [2.39268585e+02, 2.53646103e+02, 5.00597395e-02],
       [8.34142609e+01, 2.41657303e+02, 2.40259767e-01],
       [1.96108932e+02, 2.36861786e+02, 6.25032127e-01],
       [1.21778404e+02, 2.34464035e+02, 7.40641832e-01],
       [2.63246185e+02, 2.32066269e+02, 2.63953675e-02],
       [1.16982880e+02, 2.32066269e+02, 5.71921282e-02],
       [2.08097717e+02, 2.32066269e+02, 5.39671108e-02],
       [1.14585121e+02, 2.34464035e+02, 9.19763595e-02],
       [1.62540298e+02, 2.34612